### ISSUE TITLE
 AI image is all crooked while the reference image is fine?

### ISSUE THREAD

**Issue by wizardnl** [jomjol/AI-on-the-edge-device#1018]
hi guys

first of all thank you for all the work and this great project. 

any idea why my AI image is all crooked while the reference image is fine? now it cant always correctly read the digits 

![alg_roi](https://user-images.githubusercontent.com/9564314/190526261-e48fa1ee-89a5-4368-81cf-29b2c76f1f79.jpg)

![download](https://user-images.githubusercontent.com/9564314/190526418-9ee55bd1-1083-415a-bde4-d4fc6dc1bf6f.png)

**Comment by jomjol** [comment]
Yes - the reference image is processed on the webserver with enhanced alignment option (anti alising, ...). This cannot be used on the esp32cam.

**Comment by wizardnl** [comment]
im sorry but i don't understand what you mean?

**Comment by jomjol** [comment]
In case a reference image is processed, the rotation is done on the local computer with a vision library inside the web server. This has advanced image processing algorithms, that make a smooth rotation.

If you later on do the processing and rotation on the esp32cam device, there is a much simpler image processing library used, due to the limited memory and computational power. Therefore there are rotation artifacts visible. This should not be a problem for the recognition, because it is consisered in the training.
