### ISSUE TITLE
Trojaner in Update.zip?

### ISSUE THREAD

**Issue by xerion3800** [jomjol/AI-on-the-edge-device#1427]
### The Problem

When i want to download the Update.zip. I get an Failure that Windows found an Virus:
![image](https://user-images.githubusercontent.com/46169403/204444038-1b31340b-bffe-44e9-a9db-f279b77fb32e.png)

![image](https://user-images.githubusercontent.com/46169403/204444125-b1c5abe3-0ff9-4de6-8c4e-bd4a4ae1da78.png)

### Version

13.0.1

### Logfile

```shell
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503
```

**Comment by caco3** [comment]
hmm, I can not reproduce this!
See https://www.virustotal.com/gui/url/177e525ef632d58afaa6a7610c95d4c16aad912b1e2bc3a8d509dec410ff6295

**Comment by caco3** [comment]
can you upload your vrrsion of the zip file there and show the results here?

**Comment by xerion3800** [comment]
No when Windows Defender is Blocking the Download i can't  upload the file ;-)

**Comment by caco3** [comment]
Can you try to download download `initial_esp32_setup.zip` or ` html-from-11.3.1.zip` from that release (https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v13.0.1)? 

They also contain exactly the same `edit_config.html` thus must also trigger a (false) alarm.

What happens when you try to download that file directly? https://raw.githubusercontent.com/jomjol/AI-on-the-edge-device/v13.0.1/sd-card/html/edit_config.html

**Comment by xerion3800** [comment]
hmm Windows makes me crazy. Now as i want again test the downloads i didn't got failure.

**Comment by caco3** [comment]
Ich bin zimlich sicher, dass das ein Problem deines Systems ist.
Ich schliesse diesen issue daher mal, Du kannst aber weiterhin deine Erkenntnisse einfügen.
