### ISSUE TITLE
Initial rotate failed

### ISSUE THREAD

**Issue by sitnikov** [jomjol/AI-on-the-edge-device#145]
![image](https://user-images.githubusercontent.com/140812/110673206-2a26bc00-81d9-11eb-8277-d4df368157bd.png)
![image](https://user-images.githubusercontent.com/140812/110676555-c1d9d980-81dc-11eb-9225-17ce1a358f0a.png)

rotate value can not save in config.ini

**Comment by jomjol** [comment]
In order to change the initial rotage angle, you firstly need to push the button "Create New Reference". After that you can adjust the setting of the angle and so on.

Best regards,
 jomjol

**Comment by jomjol** [comment]
Maybe your reference positions are not recognized. The image is very unsharp. Firstly you should adjust manually the sharpness on the objective of the camera.

**Comment by sitnikov** [comment]
New image
![image](https://user-images.githubusercontent.com/140812/111039853-edf19680-8438-11eb-83ea-615507c28889.png)
![image](https://user-images.githubusercontent.com/140812/111039867-0bbefb80-8439-11eb-9cb5-8e45bed82509.png)


**Initial Rotate in Ref image page was  62**

**Comment by jomjol** [comment]
Did you save it before restart? Maybe there is a bug somewhere - not know yet. You can also write the 62 by hand in the ini-file for testing

**Comment by sitnikov** [comment]
yes, device restarted

After reboot
![image](https://user-images.githubusercontent.com/140812/111043862-b4775600-844d-11eb-8dea-3ae66d15f5f1.png)

3-5 min later

![image](https://user-images.githubusercontent.com/140812/111043882-c9ec8000-844d-11eb-8094-613a93b104f7.png)

**Comment by sitnikov** [comment]
10 min late, real value 713.26

![image](https://user-images.githubusercontent.com/140812/111044172-97dc1d80-844f-11eb-8b13-a6b2fcb56c00.png)

**Comment by sitnikov** [comment]
i will try reprint lower ring from black pla (current color - green)

**Comment by jomjol** [comment]
It looks like the contrast of your camera is limited - no reason why, because there is currently not dedicated settings for this. 
The changing of the colour is comming from the usage FixedExposre. Please try the following:
* Disable fixed Exposure: `FixedExposure = false`
* Disable the Brightness settings by commenting it out: `;Brigthness=-2`

With this taking the image will take about 5 seconds longer, but the colour shift should be gone and the camera is used in fully automated mode. Maybe this helps. Let me know.

Best regards,
  jomjol

**Comment by sitnikov** [comment]
adapter reprinted with black pla

FixedExposure = false
Brigthness disabled

result

![image](https://user-images.githubusercontent.com/140812/111073342-fe604a80-84e6-11eb-98c7-bd420b1dcb65.png)

**Comment by jomjol** [comment]
Not yet a really good result. Did you play with the focus and try to optimize it?
I would leave the aspect ratio for the digits as they have been at the beginning (20/32) and make a bit more space around the digits - see mine for example:
![grafik](https://user-images.githubusercontent.com/30766535/111077633-007bd680-84f2-11eb-819b-b09d52387fba.png)
It does not mater, if they overlap a little bit.
Best regards,
  jomjol

**Comment by sitnikov** [comment]
Initial rotation look as fixed

but recognitions is not ok yet

![image](https://user-images.githubusercontent.com/140812/111904316-fb1d0f80-8a4e-11eb-8e9d-587f3aed3dfd.png)


may be you have any ideas ?

**Comment by jomjol** [comment]
Your Image has a relatively low contrast and quality. I never saw digits with such a low contrast or so much noise in the background. For example see some typical images below:


![a](https://user-images.githubusercontent.com/30766535/111910498-eac26000-8a61-11eb-92ca-85db7ef29d07.jpg)![c1](https://user-images.githubusercontent.com/30766535/111910505-f3b33180-8a61-11eb-8646-383a0ca95c06.jpg)![10_ROI5_20210218-115255](https://user-images.githubusercontent.com/30766535/111910511-f9a91280-8a61-11eb-8127-29ed06013187.jpg)![b](https://user-images.githubusercontent.com/30766535/111910524-0463a780-8a62-11eb-9c63-0bbed9d6b86f.jpg)


Maybe this is an issue of the focus or maybe the camera has a problem. Because minimum the black background is much darker and not so noise. Do you know the reason for this?

If you cannot increase the image quality, then I can offer to test, if I can incorporate your digits in the next training session. For this I need 2-4 images of each digit (0, 1, ..., 9) and type (white on black, white on red). This you can get by switching on the logging.

**Comment by sitnikov** [comment]
Will try fix image quality

But one more "strange" on recognition page. Pls see screenshot

![image](https://user-images.githubusercontent.com/140812/111917692-178a6d80-8a8a-11eb-8042-552621c17a93.png)

**Comment by jomjol** [comment]
Can you send me your config.ini. I assume, that you have used the same name for two ROIs.

**Comment by sitnikov** [comment]
Yes, you are right

ROI6 320 150 33 53
ROI6 353 150 33 53

**Comment by jomjol** [comment]
Just rename one of it and you will see the correct images.
