### ISSUE TITLE
New Training Data - Enermess Needle 0.001 

### ISSUE THREAD

**Issue by marc4s** [jomjol/AI-on-the-edge-device#1580]
### Files

[Tensorflow-Data-Needle-03.zip](https://github.com/jomjol/AI-on-the-edge-device/files/10222210/Tensorflow-Data-Needle-03.zip)

would be great if you could add this images to your training data as I do not feel ready to create own training data.
I just found that this type of needle is missing in your data for some of the values and this correlate with the bad recgonition of the value here at home. most of the time this needle creates wrong data which results in no upodates due to negative rate or too much difference to pre value...

thanks for updating

**Comment by jomjol** [comment]
I tested the training yesterday with the first data. The result was really not very promising. The overall net was getting pretty bad with deviatations up to 30%.
Maybe this kind of needle is too complicated (very small needle only, ...). I will not publish this network now, because most of the users will be very disapointed with it.
Training also only makes sense, if there is a full set of images of about 200 images (2x per number). If you can provide it, I will try the training again.

**Comment by haverland** [comment]
@jomjol: I've relabeled it and run the models class100 with success. With cont I've got not better results and working on it currently.

**Comment by jomjol** [comment]
Great - thanks!

**Comment by caco3** [comment]
please reopen if you still need to extend training data
