### ISSUE TITLE
CONT-PostProcessing missing Numbers (N)->send-previous number not working?

### ISSUE THREAD

**Issue by marc4s** [jomjol/AI-on-the-edge-device#1820]
### The Problem

I am still on 12.0.1 as my devices are not stable with all the 13.x releases, so I imported the latest TFLite Files from 13.0.8
Currently I am using for the digitals the CONT File as sometimes the numbers are not recognized correct.
But from my understanding when the digits are shifting and the number is partly visible the N should not be sent outside. it should use the previous number. 

but it does sent out the N - do I need to change configuration?

![Zaehler2023-01-13 06-46-36](https://user-images.githubusercontent.com/93420756/212255477-19bb59d6-01d3-4ec1-8260-f1c5cc283d7d.png)
![HomeAssistant2023-01-13 06-46-16](https://user-images.githubusercontent.com/93420756/212255494-56116fbc-7450-4ce2-bbb9-9f16aa04201b.png)

### Version

12.0.1

### Logfile

```shell
should not be needed
```

### Expected Behavior

sent the privous number instead of N

**Comment by jomjol** [comment]
Even in the cont networks not all values are accepted, because sometime the recognition propability is very low. 
Every neural output delivers something like a probability value between 0 and 1. The higher the number, the better the detection.

In the expert settings, there is a parameter to controll this:
![grafik](https://user-images.githubusercontent.com/30766535/212471647-5623d511-6778-4e58-b15f-203514c5604d.png)

This threasholds is a value, above which the value is accepted as good. If the value is below, still a "N" is used.

If you want to have no "N" you can set the threashold to "0"

**Comment by marc4s** [comment]
thanks a lot for the hint. will try this.
is it known and normal that if there was an N value (PRE was still fine when I last checked) and the next value without N is much higher that is not checked against the PRE Value (because it was much higher it should be blocked by "rate to high")
