### ISSUE TITLE
httpd_txrx: httpd_sock_err: error in recv : 104

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1869]
When refreshing/using the Web UI, we sporadically see this error:

`W (120047) httpd_txrx: httpd_sock_err: error in recv : 104`

**Comment by caco3** [comment]
https://github.com/espressif/esp-idf/issues/7315 => closed without a solution!

**Comment by CharlesScoville** [comment]
I posted in the issue you linked to just a few hours ago with relevant information.

From that discussion, and my own Wireshark examination, I agree with @ESP-YJM that the issue is caused by the client sending "RST" to close the connection, instead of "FIN".

We should also observe that this is a "warning" not an "error." That is why it is yellow in color, and also why it starts with a [W].

...

One could say that this is the clients fault, for it is not terminating the connection in an expected and compliant way. On the other hand, one could say that it is the responsibility for any dev that makes or maintains a network facing application to handle any and all inputs being given to it safely and gracefully. One should never assume that all clients that attach to your application are polished and friendly; some are simply broken, some are actively malicious.

... I don't really think the current response from the httpd is as graceful as it could be.

**Comment by jomjol** [comment]
Close as not critical.

**Comment by dronn1974** [comment]
I also ran into this problem, I can't log in to the web interface. However, I managed to log in a couple of times, but after restarting, there is no web interface again. Each time you try to log in to the web interface, the following line is displayed in the log httpd_txrx: httpd_sock_err: error in recv : 104

**Comment by caco3** [comment]
> I also ran into this problem, I can't log in to the web interface. However, I managed to log in a couple of times, but after restarting, there is no web interface again. Each time you try to log in to the web interface, the following line is displayed in the log httpd_txrx: httpd_sock_err: error in recv : 104

What is your RSSI?
Can you try with a different webbrowser and accesspoint?
Can you try with a different SD-card?
Usually the issues are related to such things.
