### ISSUE TITLE
monitor its own battery level

### ISSUE THREAD

**Issue by lakusz1github** [jomjol/AI-on-the-edge-device#188]
Hi

Many thanks for a brilliant project !

My ESP32-CAM is powered by battery, and my question is, how to add these part of code (https://youtu.be/5JIJO1swQPE?t=530) to these project to present current voltage on main page ?

**Comment by jomjol** [comment]
I would not recommend to do that. The power demand for the calculation is rather high (1-2 minutes w/ full power). Therefore a battery is most propably not lasting very long.

But in principle:
Well, due to the high amount of devices (SD-card, camera, PSRAM) you're running low on free accesible GPIOs. There are basically 2 available in principle. You would need to make your own FreeRTOS-task, that frequently tests the voltage on one of these ports and a webserver, that reacts on a dedicated URL.

I'm not planning to implement it by myself, but I can support you.

**Comment by lakusz1github** [comment]
Thx for comment. Now i try measure how long it works on battery, then i decide it make sense or not.

**Comment by jomjol** [comment]
Closing this issue for the moment. Please feel free to reopen or make a new one in case questions arise

**Comment by wartih** [comment]
> Thx for comment. Now i try measure how long it works on battery, then i decide it make sense or not.

I was planning to use the battery. Could you share your test result?

**Comment by monocycler** [comment]
I am trying to get this to work with a small solar panel and an 18650 Li-ion battery. Anyone else tried that?

**Comment by coonha** [comment]
Hallo alle miteinander, 
ich möchte mein ESP32-Cam mit AI-on-the-edge auch über ein 18650er Akkupack betreiben, da ich am Zähler keinen Stromanschluss habe. 
Um die Batterie zu messen, habe ich einen Spannungsteiler zwischen Batterie und GPIO12 angeschlossen. 
MQTT liefert mir an GPIO auch abwechselnd true oder false (bzw. high/low) 
-> aber: wie bekomme ich es hin, das mir der reale Wert (analog) angezeigt wird? 
Kann mir jemand sagen, was ich dazu wo einstellen muss?
Vielen Dank schonmal!
