### ISSUE TITLE
Postprocessing individual parameters: Issue with display of parameters

### ISSUE THREAD

**Issue by Slider0007** [jomjol/AI-on-the-edge-device#2077]
### The Problem

@caco3: In latest rolling postprocessing individual parameters not shown anymore even in config.ini set correctly. Processing is still working, so it seems a visulization issue. In 15.0.1 it is OK.
Most likely related to missing numbers name...

### Version

Rolling

### Logfile

```shell
n.a.
```

### Screenshots

WebUI:
![image](https://user-images.githubusercontent.com/115730895/221364553-8b200553-15f3-4568-8499-28200a3ddce5.png)

config.ini
![image](https://user-images.githubusercontent.com/115730895/221364476-440c0e6d-0034-42d6-bdae-1a3749c6e1cc.png)

**Comment by caco3** [comment]
Fixed in https://github.com/jomjol/AI-on-the-edge-device/pull/2082

I accidentally deleted that part in https://github.com/jomjol/AI-on-the-edge-device/commit/886cd4ffa510984cc1e38702cb16ac8d6b1b2de0#diff-a5697edb14c8de88b221309f55facd517353ada57d0e18b22b2ca04306d79317L1418
(I thought it is a duplicate due to merging)
