### ISSUE TITLE
Device not reachable After some hours 

### ISSUE THREAD

**Issue by Sandmanyz** [jomjol/AI-on-the-edge-device#2313]
### The Problem

After Update to v15.1.1 the Device is not reachable after some hours. REST API and Webinterface are not reachable.
I don‘t find something in the Logfiles that helps.

Version 15.0.1 run stable.

We discuss it here…
https://forum.iobroker.net/topic/36622/wasserz%C3%A4hler-version-2-all-in-device/

### Version

15.1.1

### Logfile

```shell
-
```

**Comment by Trabbi1999** [comment]
I have this issue aswell or the device reports  a uptime of a few minutes/seconds, the image is is not displayed and it says (delayed):

![grafik](https://user-images.githubusercontent.com/101253671/232152217-5fef0c30-4362-472f-813d-5c8a9a02208c.png)

My Gas Meter device  had the issue that during update to the latest version the webinterface did not update and therefore it messed up, it did not find it config file anymore because it had a different file extension. Now my Water meter seems to have the same issue, it said "Website not reachable", after a reboot it shows no information at all
