### ISSUE TITLE
LED are broken or turn off ?

### ISSUE THREAD

**Issue by lakusz1github** [jomjol/AI-on-the-edge-device#248]
I made OTA upgrade, and after LED stop flash during boot up, and during make photo these mean my LED are broken ?

And second observation is, ESP is not responding after few minutes :(

**Comment by jomjol** [comment]
Sorry, this is not enough information. If an OTA upgrade fails, this is normally not a problem. Because then the old firmware will be used. Did you upgrade the html.zip as well?
Please be patient in the html access to the ESP. The webserver has only very limited capacities. Therefore it reacts very slow. Multiple access is a problem and might result in a reboot.

**Comment by lakusz1github** [comment]
Before when i run AI-on-the-edge, white LED Flash one time, now nothing flash :(

**Comment by lakusz1github** [comment]
Reflash over programmer, and now looks fine, but, after boot, White LED not flash with full power, only ca 5-10% . But i check it on new ESP32 and is the same, so it looks like, it change on firmware level. Can you confirm that ?

**Comment by jomjol** [comment]
No, I cannot confirm this. There is no change on the firmware regarding this. I assume a hardware error there.

**Comment by jomjol** [comment]
I will close this for the time being, as no more discussion at the moment. Please reopen in case of further needs.
