### ISSUE TITLE
ESP Now as alternative to Wifi

### ISSUE THREAD

**Issue by trantoriana** [jomjol/AI-on-the-edge-device#256]
Hi,

I use this project for a watermeter pretty much as is however, I would also like to us this for my gasmeter.

Unfortunately for me, that meter is about 60 meters away and without access to power and wifi.

I would be able to run this most likely on a solar-battery mode but wifi range will not be good.
ESP32 have a slimmer and more power sufficient mode build in called ESP-NOW:

* https://www.espressif.com/en/products/software/esp-now/overview

It would be good if instead of wifi, it would be able to enable a esp-now connection to a dedicated other esp device.

When setting up the device and testing purposes, one could configure wifi. But once all is setup, a switch to ESP NOW mode should just post the value, rate and other numbers over esp now.

This would allow a remote solar/battery driven meter still to be reporting data to the network.

I know my case could be very special, yet it still may be a good way to extend the usage of ai-on-the-edge for more extreme cases.

Thanks for considering, 

Tran

P.S. Otherwise it is an awesome project

**Comment by Kalafkalasch** [comment]
First let me tell you (jomjol) that this is a great system that you set up here.

I also have a greater distance to bridge and can't use WiFi except for the configuration.
I would really like to have an IO can disable all Radio (WiFi).

For me it would be sufficient if the IO is checked only on bootup, meaning that I have to restart the device in order to disable WiFi and also have to reset the chip in order to reenable it.

I am reading the values via UART and sending them home via an 343MHz Wireless Connection.

**Comment by jomjol** [comment]
Technically possible, but I assume rather a solution for a very small number of users. Currently I don't have the capacity to follow this issue. But if you adapt the code, I can check, if I can incorporate it.
