### ISSUE TITLE
Slow UI, unusable

### ISSUE THREAD

**Issue by arazok** [jomjol/AI-on-the-edge-device#2604]
### The Problem

Hi, I have now 2 different esp32 cam hw from 2 different sources (also from a link mentioned here) and also 2 sd cards.
But with both, after flashing latest release 15.3.0, it is nearly impossible to access the webpage. Building it up needs up to 6 minutes. Also pinging the machine ends up in a lot of errors/timeouts. 
What can I do ? 

Have other users the same problem ? 

### Version

15.3.0

### Logfile

```shell
cannot be provided, hanging when accessing it
```

**Comment by jwfukkink** [comment]
At first I wanted to attach an external antenne but that requires re-soldering of a very small jumper connection.

It turns out that putting a piece of sticky aluminium tape (copper tape also works) at the backside of where the Wifi antenne is, solves the connectivity problem very well (see photo)

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/12450719/1dacc9ff-4b2d-4f60-bf6f-b4007cbad5d3)

**Comment by arazok** [comment]
@jwfukkink : Good idea ! I used aluminium tape as you stated. The RSSI value didn’t decrease (still -77 dbm) but now the web ui is much faster and responding ! 
Thanks !

**Comment by arazok** [comment]
can be closed, then

**Comment by friedpa** [comment]
You can close the issue, just scroll up and click the close button
