### ISSUE TITLE
MQTT TLS (Fingerprint)

### ISSUE THREAD

**Issue by Joci78** [jomjol/AI-on-the-edge-device#2625]
### The Feature

Dear Developer,

It would be good if you know about MQTT TLS communication. Tasmota's solution works perfectly (fingerprint). I could imagine something similar here.

Best regards,
Joc

**Comment by caco3** [comment]
Please add more information, eg. a link to the Tasmota doc/spec/implementation.

**Comment by Joci78** [comment]
Tasmota documentation page:
https://tasmota.github.io/docs/TLS/

**Comment by LordGuilly** [comment]
I submitted a PR to use certificates with MQTT, I tested with AWS, it uses the ESP libraries

**Comment by caco3** [comment]
Nice work! I will have a look on https://github.com/jomjol/AI-on-the-edge-device/pull/2651 end of next week as I am on holiday now.

Since you added new parameters, we also have to update the documentation.
Can you create the pages `CACert.md`, `ClientCert.md` and `ClientKey.md` in https://github.com/jomjol/AI-on-the-edge-device-docs/tree/main/param-docs/parameter-pages/MQTT? They then will be used for the tooltips on the UI.

Orient yourself on the other files. Also i think this should be expert parameters.

**Comment by bucklevision** [comment]
Super keen to have TLS support, my broker wants to go 8883 only soon and I'm keen not to lose functionality!

**Comment by caco3** [comment]
I could not test it myself but I merged it now.

Please test it and give a feedback here!
