### ISSUE TITLE
 prevalue.ini mit invaliden Nachkommastellen 

### ISSUE THREAD

**Issue by mdax82** [jomjol/AI-on-the-edge-device#275]
prevalue.ini wird der Wert z.B. wie folgt gespeichert:

main 2021-07-16T12:54:55 308.109985

jedoch habe ich nur zwei Analog ROI eingerichtet und ExtendedResolution auch auf "false" - wie kommen denn die weiteren Nachkommastellen zustande?

Hin und wieder führ das zu
"error":"Neg. Rate - Read: 308.10 - Raw: 00308.10 - Pre: 308.100006 "

-> "Die letzte Ziffer kommt davon, dass ich dort noch recht stupide einfach einen float-Wert in einen String umwandle und nicht die letzten Ziffern abschneide. "

**Comment by stroebjo** [comment]
I noticed the same behaviour. I have one decimal and the last value was something like 55.2, the next value was correctly identified as 55.3, but the error for to big of a difference was displayed (_Rate too high - Read 55.2. - Pre: 55.3_). I have one decimal and `PreValueUse=True`. The `config/prevalue.ini` shows `55.199219`. 

I tried to look at the code, I suppose the check for the delta in https://github.com/jomjol/AI-on-the-edge-device/blob/03b5e36114c0fc834d66105441cd7bb653e2a91f/code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp#L602 could fail, since it uses the unrounded `NUMBERS[index]->PreValue`? In each case I think it would be good, to apply the `RundeOutput()` call when saving the `prevalue.ini` to prevent confusions?

https://github.com/jomjol/AI-on-the-edge-device/blob/03b5e36114c0fc834d66105441cd7bb653e2a91f/code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp#L211

**Comment by jomjol** [comment]
Error correctin in just release rolling

**Comment by mdax82** [comment]
switched to rolling, looks good so far! 👍 danke!
