### ISSUE TITLE
After updating to 15.5.0, problems restarted due to interruption of the operating voltage

### ISSUE THREAD

**Issue by Himbi777** [jomjol/AI-on-the-edge-device#2865]
### The Problem

Three days ago I performed the OTA upgrade to 15.5.0 (unfortunately I no longer remember the previous firmware status).
The update itself worked well.
The ESP only no longer boots after the operating voltage has been switched off and on again.
It goes into flashing mode 3xred - 2xred - which indicates an SD card error.
After pressing the reset button several times - the ESP caught itself again - but the error remains when you restart by switching on the operating voltage.
Now the real problem:
Even a complete new installation fails - even with older firmware.
I have two ESP32-CAM and two SD cards - I can't get any combination to work.
Greetings Gerhard

### Version

15.5.0

### Logfile

```shell
not available
```

**Comment by spanzetta** [comment]
Same or very similar situation happened to me.. I did open a bug but I was told that my problem is due to a wrong power supply..
At least it's not only me

**Comment by sosnek1** [comment]
Same here - tried with another card (as the flashing indicated SD problem) it seems to work but is lagging.

Hope will be fixed soon

**Comment by SybexX** [comment]
SD card is no longer recognized after update 15.5.0 #2863

**Comment by PatrickGlatz** [comment]
Same here! Also updated via new manual update and directly got 3x - 2x flashing. The sd card itself is readable on the Mac (god bless, now I have my configuration saved 😬). I tried it a few times, also with power unplug + replug. Finally tried a new sd card, which somehow worked. After 7hrs again flashing led 3x - 2x. I then only restarted and it was again working. Now the webui is messed up, thousands of wrong characters are shown, but the AIoE is working in the background 
![IMG_8772](https://github.com/jomjol/AI-on-the-edge-device/assets/26554156/28639ee7-660b-4279-95bd-631125d7b2c2)

**Comment by SybexX** [comment]
@Himbi777 @sosnek1 @spanzetta Please test this firmware and report whether it works now.

[AI-on-the-edge-device_v15.5.0.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14168221/AI-on-the-edge-device_v15.5.0.zip)

**Comment by caco3** [comment]
Just some thoughts:
The title of this issue refers to power issues, but you guys all mention issues with the SD-Card.

In 15.5 we updated the ESP Framework and added a patch regarding SD-Card trimming. SO there can be changes regardings SD-Cards support. This currently investigated in https://github.com/jomjol/AI-on-the-edge-device/discussions/2863, thanks to @SybexX 

**However**, independently how the firmware changed, this can not lead to power supply issues! If your device restarts and shows a **brownout** as the restart reason in the log, this simply means your power supply is not good enough!
Sadly, such a crash could corrupt the filesystem on the SD-Card. To my knowledge there is not much what we can do against it as we simply use the functionality form the ESP framework (IDF).

Also to note, I have 2 devices running since >1 year, with excessive logging to the SD-Cards, and I never had a bad SD-Card!

**Comment by Himbi777** [comment]
Today I downgraded the ESP32 to 15.4.0, everything is working fine again.  So it's the framework and not the SD cards or the power supply.

**Comment by SybexX** [comment]
@Himbi777 Defenetively it depends on your hardware, either some pullups are missing or aren't even there....
If it was the firmware, all users would have problems, but this is not the case.
I have two ESP32-Cam in use and both work, with v15.3.0, v15.4.0 and 15.5.0
The problems with Pullups have been known for a long time and if you search thoroughly on the Internet you will find dozens of pages about them.
Nevertheless, some users try to compensate for such problems in their free time.
But instead of accepting help and helping to solve this problem, they simply blame the firmware.

**Comment by Himbi777** [comment]
@SybexX , sorry maybe I didn't express myself a bit clearly.  I trigger the restarts themselves (once a day) but the problem that the device no longer starts after the restart is my real problem.  And this error is described in detail in discussion #2683 .
I do Not use any pullups, only the esp and the cam.
Thanks Gerhard

**Comment by sosnek1** [comment]
> @Himbi777 @sosnek1 @spanzetta Please test this firmware and report whether it works now.
> 
> [AI-on-the-edge-device_v15.5.0.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14168221/AI-on-the-edge-device_v15.5.0.zip)

it happened again ...

**Comment by SybexX** [comment]
@sosnek1 Does any version work for you, 15.3.0 15.4.0...?

**Comment by sosnek1** [comment]
Just performed the downgrade to 15.4.0 ... seems to work.

Will wait for the permanent fix in 15.5.x or 15.6

**Comment by Himbi777** [comment]
Hi, 

I'll test the firmware tomorrow and report back with the result

Greetings Gerhard

**Comment by PatrickGlatz** [comment]
Short intermediate report: still no issues since 40hrs. I tested soft reboot via the menu as well as just unplug and replug the power supply! Great work @SybexX  ! Thanks!

**Comment by SybexX** [comment]
@PatrickGlatz With the firmware that was last posted here, I fixed the error with the wrong version

**Comment by Himbi777** [comment]
> @sosnek1 But waiting doesn't help, because if we don't know what's causing your problem, we can't do anything about it. My changed firmware seems to work for the others. #2863 [AI-on-the-edge-device_v15.5.0.zip](https://github.com/jomjol/AI-on-the-edge-device/files/14214282/AI-on-the-edge-device_v15.5.0.zip) Please always test with the SD card files to avoid subsequent errors.

I tested this version and it worked.
Greetings Gerhard

**Comment by caco3** [comment]
[v15.6.0](https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.6.0) is out now.
