### ISSUE TITLE
Rate too high due to float rounding issue with MaxRateValue and decimals

### ISSUE THREAD

**Issue by stroebjo** [jomjol/AI-on-the-edge-device#288]
The sanity check regarding the max rate value might fail, in combination with decimal values. For example with the current meter value of `25763.2` and the next, correctly identified, value of `25763.3` the interface shows the error `Rate too high - Read:  25763.3 - Pre:  25763.2`:

![meter_rate_too_high](https://user-images.githubusercontent.com/1481657/126863620-4522d395-ee3a-44bb-937d-97c7166b0f3d.png)

The check is performed in this code: 

https://github.com/jomjol/AI-on-the-edge-device/blob/master/code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp#L602-L607

Due to the usage of floats, the difference might be slightly larger the configured `MaxRateValue`. I reprodocued the error with this C++ program: 

```c++
#include <iostream>

int main() {
    float value = 25763.3;
    float preValue = 25763.2;
    float maxRateValue = 0.1;
    
    if (abs( value -  preValue) >  maxRateValue) {
        std::cout << "too high." << " delta: " << abs( value -  preValue) << ", maxRate: " << maxRateValue << "\n";
    } 
}
```

For my case I fixed the calculation by "removing" the decimal and casting the values in the if-statement to `int`: 

```c++
if (NUMBERS[j]->useMaxRateValue && 
      (abs((int) (NUMBERS[j]->Value*10) - (int) (NUMBERS[j]->PreValue*10)) > 
      (int) (NUMBERS[j]->MaxRateValue*10)))
```

I think a solution could be to internally use `int` and "insert" the decimal places during rendering/publishing the read sensor value? Though the interface configuration and maybe other places could be difficult? 

I have the following configuration:

Setting | Value
------------ | -------------
`PreValueUse` | `true`
`DecimalShift ` | `-1`
`MaxRateValue` | `0.1`

**Comment by jomjol** [comment]
Hi,
thanks for the detailed analysis and yes you are right, the internal calculation is done on the base of c++ float types, therefore typical differences between internal and pure decimal description arise (like you proofed with your code). Changing internal to an integer would solve the problem. But this would take quite some more changes, therefore currently I'm not planning to follow this approach.
You could circument the problem, by sligthly increasing the maximum rate value (e.g. 0.11 instead of 0.1). 
Additionally I would not recommend to use the resolution of the last digit as the maximum change rate allowed, as any imperfect recognition always will stop the further reading.
