### ISSUE TITLE
it don't recognize the digital numbers

### ISSUE THREAD

**Issue by radebold** [jomjol/AI-on-the-edge-device#293]
I hope you can tell me, what I have to do.
It don't recognize the digitals. I running with the actually version 8.0.3

![image](https://user-images.githubusercontent.com/25064101/127044561-a7b085a0-8bbc-4398-938b-9279c1d94317.png)

my config.ini

`[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 3
LogfileRetentionInDays = 15
Brightness = -100
;Contrast = 0
;Saturation = 0
ImageQuality = 5
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 25
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 200 184
/config/ref1.jpg 464 133

[Digits]
Model = /config/dig0870s3q.tflite
LogImageLocation = /log/digit
LogfileRetentionInDays = 3
ModelInputSize = 20 32
default.1 217 116 38 64
default.2 263 116 38 64
default.3 310 116 38 64
default.4 356 116 38 64
default.5 403 116 38 64

[Analog]
Model = /config/ana0700s1lq.tflite
LogImageLocation = /log/analog
LogfileRetentionInDays = 3
ModelInputSize = 32 32
ExtendedResolution = false
default.analog1 447 221 95 95
default.analog2 392 322 95 95
default.analog3 295 363 95 95
default.analog4 172 315 95 95

[PostProcessing]
;default.DecimalShift = 
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
;default.MaxRateValue = 
ErrorMessage = true
;CheckDigitIncreaseConsistency = true

[MQTT]
Uri = mqtt://192.168.178.133:1885
MainTopic = wasserzaehler
;ClientID = wasser
;user = USERNAME
;password = PASSWORD

;[GPIO]
;MainTopicMQTT = wasserzaehler/GPIO
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 

[AutoTimer]
AutoStart = true
Intervall = 4.85

[Debug]
Logfile = true
LogfileRetentionInDays = 3

[System]
TimeZone = CET-1CEST
TimeServer = fritz.box
;AutoAdjustSummertime = 
Hostname = watermeter
;SetupMode = false
`

thanks for supporting me.

Thomas

**Comment by friedpa** [comment]
The reflections in the picture are too high (not enough contrast). See the forum how you can get a better picture. I see also that there is a "bar" thru the digits, which makes the digits not useable ....

**Comment by jomjol** [comment]
Settings in general are very well and accurate. @friedpa's comment is right, but it should recognize at least some of the digits. 
There was one version of tflite, that had a problem with strong contrast images (due to an error in the quantization of the network weights). This is corrected in newer versions of the tflite. Can you try to exchange the neural network file for the digits like follows:
- upload a new tflite-file to the `/config` directory. 
Please use the following: https://github.com/jomjol/AI-on-the-edge-device/blob/master/sd-card/config/dig1100s2q.tflite
- Update the `config.ini` with the new filename: `Model = /config/dig1100s2q.tflite`
- Reboot

**Comment by radebold** [comment]
thx, now it works better :-)
