### ISSUE TITLE
Firmware Update per API Call

### ISSUE THREAD

**Issue by svalcken** [jomjol/AI-on-the-edge-device#2977]
### The Feature

Please Add an api call for update firmware.
Also an api call for check of new firmware and current firmware.

And periodic check for new Versions. Thanks

**Comment by caco3** [comment]
This really is an advanced request for power users!
I don't think we would implement this, especially since most users never will need this.

> Please Add an api call for update firmware.

You can already use the existing REST API to do this.
The API are not documented but I am sure you can find them out by monitoring the browser requests.

> Also an api call for check of new firmware and current firmware.

We did not implement this on purpose as most users do not want to have devices calling "Home".
The Update page documents how you can get informed about new releases.

> And periodic check for new Versions. Thanks

See above
