### ISSUE TITLE
Adding API Calls for read and write configuration

### ISSUE THREAD

**Issue by svalcken** [jomjol/AI-on-the-edge-device#2978]
### The Feature

Add an API for read and write complete configuration.
Add also API calls for read and write from single parameters.

Also an API for read and write additional files for SD cards

As extension also API calls for generate new reference picture, settings for alignment and the rois.

Thanks

**Comment by caco3** [comment]
This really is an advanced request for power users!
I don't think we would implement this, especially since it would require extra ressourced (RAM) for something most users will never need.
Also, you could do it already now, using the APIs to delete the config file, upload the new config file and restart. They are not documented but I am sure you can find them out by monitoring the browser requests.
