### ISSUE TITLE
Please fix Typo

### ISSUE THREAD

**Issue by TBobsin** [jomjol/AI-on-the-edge-device#2981]
### The Problem

Hello, 
the list of dig-class100-*.tfl files is not sorted correctly because hyphen and underscore are used. 
I would also like a better overview of which class would fit which numbers best. 

### Version

Release: v15.7.0 (Commit: 0d0b018+)

### Logfile

```shell
no log needet
```

### Expected Behavior

equal hyphen or underscore

**Comment by caco3** [comment]
There was only one file which had a dash instead of an underscore, see https://github.com/jomjol/AI-on-the-edge-device/commit/08a350172d03f1b011d986386ab80b04cbbf9f6d

If it annoys you, you can rename them yourself or delete the unused one.

An explanation is available in our documentation: https://jomjol.github.io/AI-on-the-edge-device-docs/Choosing-the-Model/
