### ISSUE TITLE
Configuration pages partially loaded with only wording but no image or configuration options.

### ISSUE THREAD

**Issue by ykcheow** [jomjol/AI-on-the-edge-device#300]
Hi, I'm having problem to configure the references as the configuration pages are partially loaded. There are only wordings but no images or settings are loaded. I have tried with the latest firmware and also v6.3.1. But both firmware are giving the same issue. I have confirmed my wifi connection is not really that congested. Could it be the SD card issue since all images are loaded from the SD card? I'm currently using 16gb SD card in FAT32 format.

I'm using a stable 5V/2A power supply and notice whenever I tried to load the page, there is increase in current drawn but hardly goes beyond 1A and the LED flash correctly during the power up.

Please advise and thanks in advance.

**Comment by jomjol** [comment]
I have a similar behaviour very rarely also in my system, but usually can explain it by a bad wlan connection. Another topic could be a problem in the browser handling. Either due to timing problems or due to the browser itself.
To exclude the wlan problem you can take your esp32cam next to your pc or router and test it there. Although the pictures have no sense, the algorithm and the server work and you can test it. If this does not solve the problem following things can be checked:

1) Change your browser. Ususally Firefox and Chrome should work fine
2) Hardware problem with SD-card or esp32cam in general. Did you run another example, where the ov2640 camera did work?

Hope this helps,
  jomjol

**Comment by jomjol** [comment]
no updates
