### ISSUE TITLE
Extend support to Gauge of Gas Tank

### ISSUE THREAD

**Issue by nos86** [jomjol/AI-on-the-edge-device#332]
Hi @jomjol,
first of all, my compliments for your incredible work.

I'm using your firmware to track the level of the gas inside the tank I have at home.
The principle is a little bit different against the flow meter you had in mind for your development, but I can confirm that it's working pretty well.

I made some few adjustment on the processed image, but it's working great. Find attached an post-processed image.
![gas_meter](https://user-images.githubusercontent.com/6265510/132131515-f811e68a-c616-47b3-84fa-3a24eb51461d.jpg)

Recognition seems pretty well ( I just flagged the possibility to have negative rate). Now the question I have is: what will it happen when I'll do a tank refill? I need to set a new pre-value manually each time?
There is any implementation of MQTT where I can set it remotely via Home Assistant?

Thank you again for your great work.

Regars,
nos86

**Comment by jomjol** [comment]
Ususally the analog meters are working very well and you don't need to block the negative values. In this case the value just will increase as soon as you do the refill and no need to adjust the prevalue, because this will adapt automatically. 
I like you implementation very much. This is one of the features I'm thinking of: usage of the tool for general pointer detection.

**Comment by jomjol** [comment]
No further acitivies currently --> close the issue
