### ISSUE TITLE
MQTT - payload format

### ISSUE THREAD

**Issue by janumix** [jomjol/AI-on-the-edge-device#344]
Hi
Is there any way to change payload format - acceptable by i.e. Domoticz ?
Here is current format I could see in Mosquitto broker:
`{"value":10170.154,"error":"no error","rate":0.000000,"timestamp":"2021-09-18T18:09:46"}`

Expceted:
`{"idx":177, "svalue": "10170.154"}`
where 177 is configurable device ID in Domoticz.
or even:
`{"idx":177, "svalue": "10172.154", "error": "no error","rate":0.000000,"timestamp":"2021-09-18T18:09:46"}`

BR

**Comment by jomjol** [comment]
Hi @janumix, 
technically this would be no problem - you could make a personal folk for this. 
Currently the format is fixed and I'm not going to change it at the moment, because then it would not work for some other users, who are used to this. I minimum know from 3 other format request in the past, all not fully compatible.
The only way would be to make the payload configurable including an update of the html and so on. 

For this I don't have the time and resources currently, but I would be happy to integrate some other effort in this.

I will put your request to the feature request list and close this issue meanwhile.
