### ISSUE TITLE
Loads of pageload errors

### ISSUE THREAD

**Issue by sygys** [jomjol/AI-on-the-edge-device#355]
Im not whats wrong but 99 out of a 100 pages i open like settings or config crashes the ESP cam. trying to change the config takes me all night. sometimes it takes me 20 tries to even get the config page opened. What is wrong? is this bad coding or is my module defect?

I really dont understand why this is programmed for the poorest hardware ever made. Cant this software be used with better/faster chipsets with a camera.

**Comment by jomjol** [comment]
Not sure about it. I observed, that the new version (8.4.0) is a bit less robust due to internal changes, that are needed for future updates. You could go back to v8.2.0, which has the old structure, but currently no drawback with respect to features.

On the other hand, I also already had a module, that turned out to be defect somehow, showing up lots of reboots. Took me a while to figure out, it was not the code.

**Comment by sygys** [comment]
then thats probably my problem too. it keeps rebooting i think

**Comment by friedpa** [comment]
I also observed that the new version is a little bit less stable. I see rounds now between max=150 and min=20m, but average by around 50-60 rounds. Prevously I always had more than 250 rounds
