### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by mansson** [jomjol/AI-on-the-edge-device#356]
I've tried two different SD cards, but the result is the same.
Says wlan.ini is locked, then heap is corrupt. I flashed the prebuilt images in 6.5.0 using esptool on Ubuntu. 
_esptool write_flash 0x01000 bootloader.bin 0x08000 partitions.bin 0x10000 firmware.bin_
All went well.
But it's not booting.
[Rebooting.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7255342/Rebooting.txt)

**Comment by jomjol** [comment]
The ESP32 is really picky with the SD card. Obiously it cannot access this. There is only one change to use a SD-card of a different brand and type. Some controllers just cannot be accessed. Unfortunatly I cannot give you an advice, which is working.

The problem here is the connection mode: 1-wire is used, due to the limited number of free GPIOs. This is much more sensitive, than the 4-wire mode.
