### ISSUE TITLE
MaxRateValue from config not considered

### ISSUE THREAD

**Issue by johannesbonn** [jomjol/AI-on-the-edge-device#382]
Hello,
First of all, thank you very much for your work. 
I have the problem that on some days I have a counter change from over 1500 Liter (1.5m3)from my watermeter. That change based on a read out failure. To avoid these errors I have set the MaxRateValue to 0.2. But this is not considered. I have noticed that all numbers in your program are separated with a decimal point but in the config it is written with a comma. When I write it with a point it is changed after saving to a comma. Is this correct or the reason for the not considered max change of the reading.

thank you for your help!

**Comment by jomjol** [comment]
Hi,
did you observe this error several times? Could you send me the corresponding part of the log file. Currently I don't know, how this can happen.
Thanks in advance,
  jomjol

**Comment by johannesbonn** [comment]
Hello,
actually everything is fine. I will keep an eye on this and will inform you. What i have to do to log these events. Actually the log files only show me:

`2021-11-18T21:35:22: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2021-11-18T21:35:23: =============================================================================================
2021-11-18T21:35:23: =================================== Main Started ============================================
2021-11-18T21:35:23: =============================================================================================
2021-11-18T23:06:16: Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
2021-11-18T23:06:16: =============================================================================================
2021-11-18T23:06:16: =================================== Main Started ============================================
2021-11-18T23:06:16: =============================================================================================`


Thank you for your help!

**Comment by friedpa** [comment]
Switch on Logging in the config.ini

**Comment by phlupp** [comment]
Hi,

actually I have the same problem since update to v10.0.2. Before it was running stable. I have switched on the logging now and will come back later with the logs.

What I have realized already is: since the update I have a lot of suddenly reboots.

![image](https://user-images.githubusercontent.com/6304863/148641431-98d1824d-0609-4cd8-b21f-ea2317bc2598.png)

Before it was running over weeks without any reboot.

![image](https://user-images.githubusercontent.com/6304863/148641495-5971f700-2e12-48b6-8dfa-5eb1eedd0be7.png)

**Comment by tunip** [comment]
I also have this issue. As I remember version 9.1.1 was fine.

See attached logfile (issue occurs in Round #14 12:55:33):
[log_2022-01-08.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7834145/log_2022-01-08.txt)


![IMG_2200](https://user-images.githubusercontent.com/11404472/148662717-bb1659ac-287c-45e4-96db-c8abd48e7ac6.jpg)

**Comment by jomjol** [comment]
There seems to be a misreading of the neural network file, which was not detected as faulty, because it was below the MaxRate of 0.2. 
Since version 10 you need to reduce the MaxRate value strongly, as it is now normalized to 1 minute. 0.2 means a water consumption of 200l/minute as maximum. In my house this is even technically not possible, therefore I have reduced it to 0.05 (50l/minute) and even this might be a bit too high.
