### ISSUE TITLE
image dislocated

### ISSUE THREAD

**Issue by TungstenE2** [jomjol/AI-on-the-edge-device#458]
After some time the overview image seems dislocated, but cam was not moved.

![grafik](https://user-images.githubusercontent.com/39955685/145986279-917daf50-36a2-4d01-8254-4181d452c195.png)

**Comment by friedpa** [comment]
This normally happens when you view via Browser and the acclocation was not finished. Open Browser and wait until the automatic refresh is done. Only if that happens always then your allocation marks are not good enough, which by the way I assume as the contrast is very poor. You can try it with clueing a black dot in the lower left corner. But as I mentioned before you should improve the sharpness of the picture!

**Comment by jomjol** [comment]
This is looking more like a misalignment. The status in the lower right corner tells me, that the alignment went wrong. Maybe due to the low contrast and not fully sharp image.

**Comment by jomjol** [comment]
Closing the issue, as currently no further discussion
