### ISSUE TITLE
Bootloop ESP32 External Illumination

### ISSUE THREAD

**Issue by Feinfinger380** [jomjol/AI-on-the-edge-device#478]
Hi Jomjol,

I use version 9.1.1 of the adapter, but I have already tested 9.2.0, behave the same way.
The esp reboots every 5 minutes.

I have tried the SD card as well as three different esp and 2 power supplies, always the same behavior.

As lighting I have 2 WS2812 and a 470uf capacitor
[watermeter logfile.txt](https://github.com/jomjol/AI-on-the-edge-device/files/7773611/watermeter.logfile.txt)
.

**Comment by speerwerfer** [comment]
https://github.com/jomjol/AI-on-the-edge-device#known-issues

**Comment by jomjol** [comment]
Hi @Feinfinger380 ,
as the reboot is randomly happening at different times and positions in the code, I'm pretty sure, that this is hardware related and not directly with the firmware. Even if you have tried several ESP, power supplied, ...

If it would be the configuration or some file on the system it should always crash at the same time in the flow.

**Comment by Feinfinger380** [comment]
I thinks its an error in the code.
Same setup, esp, camera module, power supply and sd card.

Firmware 8.4.0 works for hours like a charme.
Firmware 9.xx reboot every 3-5 minutes.

**Comment by jomjol** [comment]
I agree with your observation. In Version 9.x there were additional libraries included and more RAM is needed due to more features. That makes it more sensitive to the reboots.

I have investigated quite a lot on this and cannot find any improvement currently.

There is no reason, why you shouldn't use version 8.4 if you don't need the features of more recent firmware.

Therefore I'm going to close the issue. In general the unstable issue is adressed and mentioned at several points in the wiki.
