### ISSUE TITLE
sdcard partition

### ISSUE THREAD

**Issue by FloMaetschke** [jomjol/AI-on-the-edge-device#557]
Please update the wiki site Installation - sdcard

Please add:

SINGLE PARTITION, MBR, FAT32 - 32K.  NOT exFAT

**Comment by jomjol** [comment]
Thanks and done.

**Comment by PatrickGlatz** [comment]
Hi @jomjol,

on the landing page it is still mentioned to format the SD card as "FAT", see here:

> Flashing the SD Card
The SD card can be setup automatically after the firmware got installed. See the [documentation](https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#remote-setup-using-the-built-in-access-point) for details. For this to work, the SD card must be **FAT formated** (which is the default on a new SD card). Alternatively the SD card still can be setup manually, see the [documentation](https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#3-sd-card) for details!
[https://github.com/jomjol/AI-on-the-edge-device](url)

whereas it is mentioned to format it to FAT32 in the later docs:
> 1.3.0.1 Notes
Following setting are necessary for formatting the SD-card: SINGLE PARTITION, MBR, FAT32 - 32K. NOT exFAT
https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#3-sd-card

Maybe it is also worth to add the following information for MACOS on arm users: For me 15.4.0 was not working when the SD card was formatted without MBR. Also - for my knowledge - it is not possible to set the cluster size properly. The most promissing command in MACOS Terminal would be (where X is the respective disk no for your SDCARD):
```
diskutil list
sudo diskutil eraseDisk FAT32 SDCARD MBRFormat /dev/diskX
```

Also it might be useful to disable Spotlight indexing for the SDCARD
```
sudo mdutil -d "/Volumes/SDCARD"
sudo mdutil -X "/Volumes/SDCARD"
dot_clean /Volumes/SDCARD
```

Still i have not confirmed, that is working for a longer time, but it is now running since 3 hrs, so also seems to be working.
My PROD meters all have a SD card now formatted with the Windows Laptop of my neighbour and are working both perfectly fine for the last 24hrs.

**Comment by Sofahamster** [comment]
Using the standard disk formatting from file explorer in Windows 11, I couldn't get this to work. I tried FAT and FAT32 as options, as well as different allocation unit sizes. Nothing seems to work. Any idea on how to format the sd card on windows so that it is compatible?

**Comment by SybexX** [comment]
how GB have your SD card?
Normally it is sufficient to format the SD in FAT32 with the default settings.
SD cards that are too large can cause problems, it is best to use up to 16GB SD.

**Comment by Sofahamster** [comment]
> how GB have your SD card? Normally it is sufficient to format the SD in FAT32 with the default settings. SD cards that are too large can cause problems, it is best to use up to 16GB SD.

Sorry I already deleted my comment after I found out that I just didn't consider that partition table on the sd card. Windows created the volume with the newer GPT partition table scheme by default. 
I switched to a linux PC and used gparted to format with MBR and used mkdosfs to finally get the right formatting.
