### ISSUE TITLE
Seven segment display recognition

### ISSUE THREAD

**Issue by harryphiles** [jomjol/AI-on-the-edge-device#571]
First of all, thank you for your work! This is awesome.

I think this is already quite capable of recognizing seven segment display.

However, my problem is that I can never get full numbers recognized--especially no luck with those middle numbers.

Can I get help for this?

Thanks in advance!

<img width="327" alt="image" src="https://user-images.githubusercontent.com/58872165/149621402-03341293-344d-4581-8242-94e0577a8fbd.png">
<img width="142" alt="image" src="https://user-images.githubusercontent.com/58872165/149621405-c48ac0d4-7f07-4b04-a1de-df4595d01586.png">

**Comment by jomjol** [comment]
This kind of number is not trained. Also they are very close to each other, so that it will be a problem with the standard expected frame of 20% (see: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration).
Maybe a dedicated neural network would be necessary. You can find a hint for training here: https://github.com/jomjol/neural-network-digital-counter-readout
But it is not very well documented, as it is normally not necessary.
