### ISSUE TITLE
MaxRateValue does not work as expected

### ISSUE THREAD

**Issue by kristk** [jomjol/AI-on-the-edge-device#627]
I have noticed an issue with the MaxRateValue after the new normalization of that value.

I have the value set to 0,03 and an update interval of 4,85. If I understand it correctly that would mean the maximal increase of the data value between two updates should be 0,1455? But I have at several occasions seen increases of the data value by far more than that. Shouldn't the MaxRateValue prevent that?

I attach a log showing such an occasion where the data value increased by 10. The images show the data value, the rate value, my setting and my current version.

<img width="1219" alt="Watermeter-reading" src="https://user-images.githubusercontent.com/484679/152108758-8a7a8637-fd99-4b8d-9fb9-c8b68139bb13.png">
<img width="1228" alt="Watermeter-rate" src="https://user-images.githubusercontent.com/484679/152108756-dee9be5b-ff80-45e0-b052-73d43ef4114b.png">
<img width="653" alt="Watermeter-settings" src="https://user-images.githubusercontent.com/484679/152108759-979818e2-beab-46fd-9890-8ee232b2ba65.png">
<img width="312" alt="Watermeter-info" src="https://user-images.githubusercontent.com/484679/152108753-2ef016f6-d13a-42bb-b043-f79179e82e89.png">

**Comment by derandi80** [comment]
Hi, an error or jump is recognized as correct over time. Because the rate decreases with time.

Ex:
MaxRateValue: 0.01 per minute
In a time window of 5 minutes, a jump of 0,05 can be possible and within half an hour a jump of 0.3 can be possible and so on ... 

Current value would be 0.02, but read from becomes 0.1. This would be an error (0.02+0.05 =0.07) after 5 minutes and would be wrong.  At the next read-out, 10 min have passed, and the rate would then be 0.1. Then the error would be OK and is accepted. 

Otherwise, look at the log file, there you can see exactly when the jump happened. A remedy could be to reduce the MaxRateValue.

**Comment by jomjol** [comment]
@derandi80 is totally right. This is a drawback of the method to use a rate as value. In one of the previous versions, the rate was just the change between the last correct detected value and the next reading. In this case the time had no influence.
I close this issue - but you can write still here and I will respond.

**Comment by kristk** [comment]
Thanks for you answers but I don't really follow. Let me give an example. The MaxRateValue is set to 0.01 per minute and the update interval is set to every 5 minutes. The first reading is done at t0 and the value is then 0. The next reading is done at t0+5min and the reading is still 0. That means that nothing has happened during the first five minutes. The third reading is done at t0+10min and now is the reading 0.06. I though this would be seen as an error because the increase in the value (0.06) is larger than the possible increase since last reading due to MaxRateValue (0.01 * 5). If I understand you correctly the possible increase is instead 0.01 * 5 * 2 because there was a reading at t0+5 with no increase in the value? I would argue that the evaluation always has to be based on the previous reading without error? Please help me understand this :)

**Comment by jomjol** [comment]
Nice example - As the reading at t0+5min was okay, the third reading as t0+10min will be rated compared to t0+5min - so it will be considered as an error, because 0.6 > 0.1*5.

The situation is different, if the reading at t0+5min would have already been an error:
Assuming, that you already had the 0.6 reading at t0+5min --> error!
Now the last correct time value is still t0. Assuming now that you read at t0+10min still the 0.6, than this would now be accepted, as 0.6 < 0.1 * 10.

Hope, that makes it a bit more clear
