### ISSUE TITLE
Failed to read existing file

### ISSUE THREAD

**Issue by cismarine** [jomjol/AI-on-the-edge-device#646]
Hi,
Thanks for the amazing tool. Unfortunately after flashing, esp32cam is connecting to network, but getting a message as in subject.
Multiple erases and flashing attempts with expresiff software and esptool command line. 
I can flash different image without issues.

**Comment by jomjol** [comment]
Looks like a problem with the sd-card - ESP32CAM is very sensitive to this. Try another one (ideally about 4 GB).

**Comment by cismarine** [comment]
I have tried quite a few. Still same error

**Comment by j3sk0** [comment]
i have the same error how did you solve it?

**Comment by infa-presales** [comment]
Same here for me. I successfully flashed with a 32GB Intensio SD Card and fetched an initial image, but the lens focus needed to be changed. So I stopped the ESP32, try to correct lens focus and reconnected. The ESP32 get the IP address (I see the DHCP log) but any attempt to reconnect was failing with error
Failed to read existing file
I also tried a brand new Samsung Evo Plus 32GB but get the same error. I will now check if I have a 4GB SD in my fundus to test with it. However it would also be great which file might be missing when accessing the SD Card

**Comment by caco3** [comment]
That's a bit odd, I have it running on my docking station as well as a battery powered labtop. In both cases it works fine!
Note that 32bit might be too large. I use 16GB with different cards and never had an issue.

**Comment by infa-presales** [comment]
Note that USB ports at PC usually allow to attach hard drives, which 
even might have a high current / power need if spin on . In the past old 
externel USB HDD drives had a Y cable. So USB ports are usually quite 
powerful.
However the cheap China USB power plugs might not be good on peak power 
need, not large enough ("expensive" in cent area) capacitors are used...
When flashing the device I also used a PC USB3 port, which have enough 
Power.


Unfortunately I cannot find the discussion at Github this mail thread 
was created of. But I have in the moment a quite strange behavior in 
number recognition, which might be caused by the poor adjustment of 
wheels and digits.
Here my current picture

which shows an error

Neg. Rate - Read: - Raw: 00367.1413 - Pre: 368.0970

as it looks suddenly the lowest value digit is again recognized as 7 and 
not as 8, so that the former value 368.0970 is larger then the actual 
when raw string 00367.1413. is converted




Is there a parameter to avoid that?
regards
     Detlef (aka infa-presales)

PS:  Nevertheless that I a really great peace of code. I was positively 
surprised, as at University I once  worked in the late 80's on Neuronal 
Networks (topic: learning behavior of back-propagation networks). The 
inherent limitation seem never allow such results, but the pure 
computational power gain we had since then brought NN into a region that 
this kind of tasks can be done. I  never expected that this will over 
the years reach a state that NN it can be really used in practice, but 
obviously I was wrong.

Zitat von CaCO3 ***@***.***>:

 > That's a bit odd, I have it running on my docking station as well as
 > a battery powered labtop. In both cases it works fine!
 > Note that 32bit might be too large. I use 16GB with different cards
 > and never had an issue.
 >
 > --
 > Reply to this email directly or view it on GitHub:
 > 
https://github.com/jomjol/AI-on-the-edge-device/issues/646#issuecomment-1275164800
 > You are receiving this because you commented.
 >
 > Message ID: 
***@***.***>

**Comment by caco3** [comment]
> Note that USB ports at PC usually allow to attach hard drives, which
even might have a high current / power need if spin on . In the past old
externel USB HDD drives had a Y cable. So USB ports are usually quite
powerful.

Yes, I am aware of this, that's why I mentioned that it successfully runs from a **battery** powered laptop. In oposite to a desktup, they usually do not allow pulling more than he 500 mA.

If power is too weak, I would expect a [Brown Out Reset](https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32s2/api-guides/fatal-errors.html#brownout)! If this is not the case on your setup, then it most likely is not a power issue!
