### ISSUE TITLE
Image incorrectly rotated during recognition

### ISSUE THREAD

**Issue by maestrx** [jomjol/AI-on-the-edge-device#652]
Reference image is self-rotated post configuration making the previously well aligned ROI positions misaligned. Thus whole reading is failed. One more symptom is that the reference image on the "Overview" page is fine, but on the "Recognition" page is rotated. Its not a environment problem (camera was nto rotated after the ref image was taken) since when I try to create a new ref image wiht the same config, the image taken fits the original one in the "Overview" page.

So something is making the image of teh taken picture during recognition rotated in some other way that the reference picture was taken...

How to debug?

Thanks

**Comment by jomjol** [comment]
Rotated images after the setup can have two reasons:
1) something went wrong during setup --> paramters and images are not stored in config.ini and the corresponsing files
2) the reference image is not perfect and cannot be detected sometimes. Use one with more contrast.

Most probably the problem is #2

**Comment by maestrx** [comment]
Ive updated the contrast values and made the image a bit darker and all is stable since than. 

Thanks for the suggestion #2, it fixed the problem.
