### ISSUE TITLE
Is it possible to recognise the last digit if it is "slow moving" ?

### ISSUE THREAD

**Issue by Robert-Riedl** [jomjol/AI-on-the-edge-device#672]
Hello,

let me preface this with some praise: This project is awesome.

Now, after some tinkering I've managed to get it to recognize the main digits, save the very last one.
I suspect because its not a clear digit, but "slow moving" - see picture (I don't know what the correct term is).

But is it even possible for the algo to recognize this digit ? I know the ROIs could be better but I doubt it would make a difference for this one, right ? Its never going to be exactly aligned, always either missing part of the digit or having another "peeking" from the bottom.

![image](https://user-images.githubusercontent.com/62740104/153872276-7f8a63d5-9947-41cd-a9c5-27a529c7c1d1.png)
  
![image](https://user-images.githubusercontent.com/62740104/153872612-9f8762c9-9973-4c6b-9225-aa8a5f42944d.png)

**Comment by jomjol** [comment]
Currently intermediate values are detected as "Not-a-Number" = N and an algo tries to replace them as good as possible from the previous value. So in general it should work with 0.1 m³ resolution until the next 0.1 digit is detected.
In one of the next versions I will implement an intermediate detection as well, but this might take some more time, because it is not too easy. 
I will close this issue for the time beeing.
