### ISSUE TITLE
training digital ROIs

### ISSUE THREAD

**Issue by steuerzentrale** [jomjol/AI-on-the-edge-device#706]
Hi there

would be glad if you could upload the attached digits to the AI, it contains every digit from 0-9 ;) many thanks for this cool project !

all the best

Andrew
[digits.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8136540/digits.zip)

**Comment by jomjol** [comment]
I will do so, but not all numbers are according to the suggested settings: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

I have excluded the following images from the training:
![9_arbitrary](https://user-images.githubusercontent.com/30766535/155834722-257057d4-f7dc-4e56-9b47-275866f83baa.jpg)![8_arbitrary](https://user-images.githubusercontent.com/30766535/155834729-eae0b07b-2c97-42d2-8313-f4a976ae7056.jpg)![6_arbitrary](https://user-images.githubusercontent.com/30766535/155834730-50f05e7d-2f97-4b73-b175-ec15cf0470d5.jpg)

I have no time to deal with this during the weekend anyway. So if you send better fitting images until tomorrow, I will start the training with a full data set otherwise I take what I have.

**Comment by steuerzentrale** [comment]
thanks, actually I would be glad if you start the training without the excluded images, I really adjusted the configuration several times and I mostly run into problems with the digit 0 or 1. many thanks!

**Comment by Gukerl** [comment]
Blöde Frage... stupid question, but isn't there the possibility to "self" train the values if there is Jupyter notebooks installed and running?

**Comment by Luc3as** [comment]
> Blöde Frage... stupid question, but isn't there the possibility to "self" train the values if there is Jupyter notebooks installed and running?

I Just wanted to ask the same, in previous version where docker container handled recognition of number I trained data on my own, and the accurracy of Reading is really good, but I think the other version of model will not fit into esp 


Thanks

**Comment by friedpa** [comment]
You can a) train your own model (see Wiki) or b) use any previous tflite file you want. I am using a tflite from the beginning of the project, as it works fine for me and my watermetter / gasmeter.
So copy the tflite file into the ESP, which give you the best results and change the file name in the config.ini accordingly.

**Comment by jomjol** [comment]
Nothing to ad to friedpa's comment :-)

Maybe the link to the training repositories:
https://github.com/jomjol/neural-network-digital-counter-readout
https://github.com/jomjol/neural-network-analog-needle-readout

or in case of training within a github action:
https://github.com/jomjol/neural-network-autotrain-digital-counter (not yet available for the analog needles)
