### ISSUE TITLE
Picture rotates after a wile of usage

### ISSUE THREAD

**Issue by Grillfreund** [jomjol/AI-on-the-edge-device#716]
Hello jomjol,

I have an little issue which appears always after a wile of using:
![image](https://user-images.githubusercontent.com/73735788/156931420-5e790fea-ca6f-4db4-a0ab-74b9fbef3f5d.png)

I haven't changed the camera orientation. And the reference image is also correct. Why is the picture rotated?

Thank you for your help
Michael

**Comment by friedpa** [comment]
As you can see the rotation was not finished. Also the Values on the right are not shown correctly. This occurs if you trigger an update of the Webpage in the middle of the "Flow"

**Comment by Grillfreund** [comment]
Thank you for your answer. But the status shows "Flow finished"...

So I think there is something else wrong.

**Comment by jomjol** [comment]
Well, the problem is rather the reference images. If one of them is not identified correctly, than this can happen. It looks like the upper one "Eigentum" is not correct identified. It has a too fine structure. I would suggest to use a different one with a more simple structure or to make an own one, e.g. by putting a white sticker with a black dot or comparable onto the glas surface.
