### ISSUE TITLE
Logic if last digit is N

### ISSUE THREAD

**Issue by JensHoRi** [jomjol/AI-on-the-edge-device#792]
One suggestion for logic of correction: 

Prevailed is actually 38,245.90

raw is 38,247.N

in this case N could be set to 0 without being wrong. Same would be if last raw is e.g.higher 7 and raw would be 38,246.N

Had same with change watermeter at 1,000 m3

old was 999.9875, raw was NN00.1235 could interpretate NN as 10 because logical could not be something else ;) 

If too complex feel free to close. But I wanted to share this

**Comment by steigerbalett** [comment]
This would be a good improvement.
My watermeter reports most of the time no value because of the last "digital"digit. It always between two states :-)
The recogniton of the anaog digits works flawless.
So could you implement, maybe optional,  a "only count up and estimate N" function.

Maybe like: If the device could not recognice the digit (N) then look at the next digit in combination with the prevalue (the logic @JensHoRi mentioned). 

- If the next digit is 1-9 the take the last recogniced number.
- If the next digit ist 0 then count up by 1 (because it has only one direction)

**Comment by jomjol** [comment]
Good idea. I'm currently working into another direction: getting rid of the "N" by detecting also intermediate results.

Problem is: this is a major change in the neural network (incl. 10x more training data), which needs to be developeded and tested. As I'm doing this in my free time, it only makes very slow progress currently. In the meantime I don't want to change too much on the running code anymore, going into a dead end (e.g. changing "N" behaviour).

Therefore I will close this issue for the time beeing and but a reference into the feature request list - just in case my other approach will fail.

**Comment by JensHoRi** [comment]
If it’s clearly known, what you need, maybe community can assist sending right formatted training data

**Comment by jomjol** [comment]
Well, currently it rather a question of the structure and algo and rather long training cycles to check if there was any progress. I would need a faster computer ;-)

Thanks for your offer.

**Comment by JensHoRi** [comment]
Just one question: 

is there an api call for stetting the prevalue? Than I would try to solve this logic in openHAB directly ;) 

Greetings,

Jens 

Mobil gesendet

**Comment by jomjol** [comment]
Yes, there is: `http://IP-ADRESS/setPreValue.html?value=123.456&numbers=XYZ`

Where XYZ the name of your number is (e.g. main)
