### ISSUE TITLE
Analog training data

### ISSUE THREAD

**Issue by Henque19** [jomjol/AI-on-the-edge-device#793]
Hi Jomjol!

Can you please train the NN with the following images?
One dial (in folder "0.01") is especially problematic as it has a wierd shape. Please let me know if you need more training data.

Thank you for your work, great project!

[analog.zip](https://github.com/jomjol/AI-on-the-edge-device/files/8605460/analog.zip)

**Comment by jomjol** [comment]
I have tested your data in a new training. Unfortunately especially the 0.01x is making trouble and the overall result not very good. As this is basically a new type of pointer, I think I need a full training set and not only some selected pictures.

That means about 100-200 images with a resolution of 0.1 (0.0, 0.1, 0.2, .... 9.7, 9.8, 9.9). Otherwise it will not train this new type correctly.

Can you make this?

**Comment by jomjol** [comment]
Closing for the time beeing. Please open new case images are availalbe
