### ISSUE TITLE
 Fine Alignment resets to 0

### ISSUE THREAD

**Issue by gimmel** [jomjol/AI-on-the-edge-device#846]
The Pre-Rotation Fine Alignment value resets to 0 after updating the reference image. It seems to be a relative value. It’s not really clear what it does.
I can enter decimal values in Pre-rotate Angle, so Fine Alignment is not necessary I think?

**Comment by JensHoRi** [comment]
For me it works fine, but agree: new reference resets fine alignment. 

But after configuration is done there is now need for new reference images, so it’s a minor bug(?) but ok, because with new reference alignment and roi always should be controlled and reconfigured.
So question: can we close the issue?

**Comment by jomjol** [comment]
The fine alignment with steps of 0.2° is only needed to get a perfect reference image. Afterwards, the normal alignment is fully sufficient.
