### ISSUE TITLE
Rolling shows only black images on configuration

### ISSUE THREAD

**Issue by aendes** [jomjol/AI-on-the-edge-device#88]
Hello,

i upgraded to the current rolling (from the last rolling)
On the alignment, refence and configuartion images i only get black images (with green configuration lines)

The main picture is visible and seems to be a current one

Thanks in advance

Andreas

**Comment by jomjol** [comment]
Hi Andreas,
this problem has not been reported yet, so I need more information to analyse it.

**Firstly:** depending on the alignment algorithm it takes up to 3 minutes, until you get a very first result. This is only true for the first run after a reboot. Background is, that one the time the algo needs to run throug to store the informations for the responses in the memory.

If this is not your problem, please do two things:
1. enable the logging in the config.ini and send me a copy of it:
```
[Debug]
Logfile = true
```
2. Can you log the serial port during one run (1-3 minutes) and send this to me, too.

Best regards,
  jomjol

**Comment by aendes** [comment]
Hello,

attached the two log files.

[logfile.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5792372/logfile.txt)
[serial_out.txt](https://github.com/jomjol/AI-on-the-edge-device/files/5792373/serial_out.txt)

**Comment by aendes** [comment]
Hi,

to verify that it is not my hardware, i made a downgrade to the current master.
Everything works with the current master.

Andreas

**Comment by jomjol** [comment]
Hi Andreas,

thanks for the log files. Your problem is really unique!
Logfile tells me, that the detection flow is running normal and results in reasonable results - maybe one digit is wrong, but never the less - there are reasonable numbers and it start the next flow as expected.
Also the serial does not show any suspicious topics on the first analysis.
And your test proves, that the hardware is okay!

Just to be sure: you down/upgraded always the firmware and the html directory in parallel?

Could you test a "dry" run on a clean setup system: format an SD-card and put on the original files from the rolling.
This should work for sure. Then you can replace the /config directory with your data and see. If then the problem is still there, we should see, which file is responsible for this. Sorry for the inconvenicance, but never had that problem before, therefore "debugging" is a little bit difficult.

Best regards,
  jomjol

**Comment by aendes** [comment]
Hello jomjol,

yes, i always upgraded firmware/html same time.

With the test to "dry" run i destroyed my setup, it will take me some time to get it back running.

sorry for the delay

Andreas

**Comment by aendes** [comment]
Hello,

with two new SD-Cards i tried to install master and rolling in a fresh installation

I was able to install master as expected.
On rolling i was not able to create a new running setup.
In the wizzard it doesn't show a picture on "Alignment Marks", on the "ROI => Analog Input" the Checkbox "enable" is re-disabled on save and says you have to enable it.
I tried to circumvent wizzard, but this also happens on the running Configuration ROI- Page

Andreas

**Comment by jomjol** [comment]
Hello Andreas,

this is really strange and your currently the only one reporting this problem. I can offer to have a personal look e.g. in a skype meeting on the weekend if you send me your contact. In what timezone are you?

Best regards,
  jomjol

**Comment by aendes** [comment]
Hello,

i am located in Germany, so you could i get to your contact data?

Andreas

**Comment by jomjol** [comment]
Hallo Andreas,
  wir können auch gerne Deutsch schreiben. Ich möchte hier nicht meine eMail oder Skype-Adresse posten. Bist du auch im iobroker Forum, openhab oder fhem aktiv? Dort können wir uns in einem privaten Chat die Kontaktdaten zusenden.
  Gruß,
    jomjol

**Comment by jomjol** [comment]
Hallo Andreas,
danke nochmal für den  Input von gestern. Ich habe jetzt mal eine neue Rolling erstellt (Update html.zip und auch firmware.bin).
Vielleicht kannst du es mal testen?
Gruß,
  jomjol

**Comment by aendes** [comment]
Hallo jomjol,

die Rolling läuft seit heute morgen ohne Probleme und zeigt alles korrekt an.

Andreas

**Comment by jomjol** [comment]
Super! Dann schließe ich jetzt den Issue. Danke nochmal für deinen Input.
