### ISSUE TITLE
Setup cannot be completed in 10.6.1

### ISSUE THREAD

**Issue by vitruvo** [jomjol/AI-on-the-edge-device#888]
My sensor stopped working a few weeks ago... so I did a full reset and put on 10.6.1
Sadly, the setup cannot be completed. once a reference image is set, the step for alignment marks cannot be initialized and I cant's complete the setup.
Mainly the issue seems to consist of 500 errors due to missing image-files and failed retrieval of configuration details which kinda messes up all following steps... 🤷‍♂️
very frustrating

**Comment by pos-ei-don** [comment]
Try a different Browser, especially mobile Browsers seem to work much Better here when I See the same Problem.

**Comment by vitruvo** [comment]
indeed, that worked! I've been able to complete the setup via safari on iPad, what makes the definition of areas a little less precise but hey - it worked!
Thanks for the hint!! ✌️

**Comment by pos-ei-don** [comment]
But would not it be Nixe to find the reason, why current Chrome and Firefox Browsers Show this behaviour?

**Comment by jomjol** [comment]
I agree, but I'm not a http developer, just a c++ developer.
So I'm happy, that this is running in one environment. If somebody can suppert: VERY WELCOME !!!!

Can you do that?

**Comment by pos-ei-don** [comment]
I think it is more c++ than http, but I didn't find a solution Till now. It seems that the old http protocol Version the esp supports is part of the Problem.

**Comment by JensHoRi** [comment]
Don’t believe so, because http is an asynchrone protocol without a standing connection. So it could only be part of the html pages or some AJAX JavaScript parts. 

Question is, if everybody has this problems? I could reconfigure with pc in actual firmware too. But have no initial setup to be done. 

It could also be a caching problem, some old JavaScript or html parts are cached not compatible with new firmware. 

Would be interesting to have a first time user to know if he has got same problems
