### ISSUE TITLE
InfluxDB feature is not working

### ISSUE THREAD

**Issue by ckoeber83** [jomjol/AI-on-the-edge-device#913]
Hi,

i'm trying to use the new InfluxDB feature to write the values direct into InfluxDB.

I try to enable InfluxDB in config.ini but it will be still disabled after safe and reboot in GUI mode:

![grafik](https://user-images.githubusercontent.com/52466072/184698622-db9dbb28-10d2-407b-96a5-130f17519433.png)

I edit the config.ini than directly and uncomment the "[InfluxDB]" and "Database" line and reboot again:

```
[InfluxDB]
Uri = http://ip:port
Database = ...
Measurement = ...
user = ...
password = ...
```

After reboot, it is still unchecked in GUI but also uncomment in config.ini. So it should be enabled but it isn't.
I'll take a look into my InfluxDB measurements and could not find the named measurements from watermeter.

So for me the InfluxDB function is not proper working actually.
Can you pls take a look into this.

Running version: master - v10.6.1 - 2022-07-24

**Comment by jomjol** [comment]
Thanks for your issue
1) I assume, that you did not use the newest html.zip. Because there at least part of your reported error was already fixed.
2) Never the less I found another smaller issue (Database was not stored in all cases) --> Corrected in the newest release (v11.0.1)

Please update your html.zip to the newest version 14.3.2. With this version, everything worked on my test system now.

![grafik](https://user-images.githubusercontent.com/30766535/184716389-d04d61ca-c4fc-4230-bc6b-efd720982011.png)
