### ISSUE TITLE
Rolling: OTA HTML update not not updates

### ISSUE THREAD

**Issue by haverland** [jomjol/AI-on-the-edge-device#959]
Used the last Rolling and updated OTA firmware + html.zip. But html is not updated any file.

The dialog shows the update is done - but comes extremely fast after clicking the update button.

Log has no error entries.

**Comment by jomjol** [comment]
@caco3 : seem there might be a problem? Did I forget something? I did not test in detail. Can you do that?

**Comment by haverland** [comment]
After manual upload all new html files the problem is still here.

**Comment by caco3** [comment]
hmm, I did not change any functional code, just moved some HTML snippeds around, see https://github.com/jomjol/AI-on-the-edge-device/compare/master...rolling#diff-71d24da02d173de1f3bfcd7509920a1350de260e33e884b79ea81804e8a147b3

Also, the pre-zipped `html.zip` is not updated yet, so a firmware update shouldn't have any impact at all, right?

**Comment by caco3** [comment]
IMO we should remove the folder `firmware` and instead automatically build them through github actions.
I don't know Github that good, but on Gitlab it would move the builded files into an artifact store, where they could get downloaded.

And when we build a new release, we should attach those artifacts (the releases atm. only contain the source code).

**Comment by haverland** [comment]
Is not the last commit on the ota-html page. 

http://watermeter1/ota?task=unziphtml did not work. But logging is on serial. I will check the serial log and give feedback.

**Comment by caco3** [comment]
I always used the upload `/html` function to test my changes, but I never saw an issue.
Note that the html folder grow by around 100 KB. So maybe you need to wait a bit longer.

Attached `html.zip` contains the stuff from rolling and the open PR https://github.com/jomjol/AI-on-the-edge-device/pull/96:
[html.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9456575/html.zip)

Note that you also have to build the firmware from this PR to have it working. Else thy css style is broken (had to add css support to the file server first, see https://github.com/jomjol/AI-on-the-edge-device/pull/960/files#diff-35448d4f323a0dd4608ebd5de5817a4e225aeb4ca3662d499ddd0a5fb7e0b36c)

**Comment by haverland** [comment]
Here the serial log. Looks like the server_ota.cpp:701. In the delete function the /sdcard/html can not be opened. 
But rest of the device works good (Webserver, logging, etc.). No idea currently why.

handler_ota_update
Query: task=unziphtml
task is foundunziphtml
␛[0;31mE (82698) file_server: Failed to stat dir : /sdcard/html/␛[0m
miniz.c version: 10.1.0
Zipfile: /sdcard/firmware/html.zip
Target Dir: /sdcard/html/
mz_zip_reader_extract_file_to_heap() failed!

**Comment by haverland** [comment]
I close it, because it looks like an issue on my device.

**Comment by caco3** [comment]
Did you test this with a newer zip file (containing my changes)?

The size grew by around 100 kBytes (uncompressed), so maybe your device runs out of memory?
Does it also happen with the release version /firmware and html)?

**Comment by haverland** [comment]
The issue is before the uncompressing. The device removes all files in /html before unzipping. And here the read of the directory fails.

**Comment by pos-ei-don** [comment]
So this issue is still valid and should be reopened? 
I experienced the same. 
?

**Comment by haverland** [comment]
> So this issue is still valid and should be reopened?
> I experienced the same.
> ?

Same log results on serial?

**Comment by caco3** [comment]
@haverland Which firmware revision and html revision did you use?
I don't think this is related to my changes to the html files (only a minor firmware change, but AFTER you had your issues), but I want to make sure.

**Comment by haverland** [comment]
I'am using rolling. 
Was the trailing slash of /sdcard/html/ (server_ota.cpp:352). 

But after removing I've got an empty html/ directory. I'm on it.

**Comment by haverland** [comment]
reopened

**Comment by cbho** [comment]
Hi,
seems like you are working hard on the OTA problem (and lots of other stuff) - your efforts are highly appreciated!

However: (Hate to raise this kind of question, but...)

If you already updated to a version with broken OTA - how do you update to the new version, that doesn't have the problem?
Might be it's not a problem at all using som workarounds - but I think descibing how to do it would be a pretty good idea...

While everybody started flashing the device by cable, not all devices are that easily accessible and having to reflash physically can turn out to be dificult (I made a device for a friend, which is now mounted in the other end of the country and therefore would have to unmounted, mailed etc., if physical update is the only way, e.g.).

Still: Thanks for all the efforts!

**Comment by jomjol** [comment]
The only way to update after a broken OTA is a flash over the serial. 

Yes, you have to unmount the device and maybe even update the alignment - Happend to me yesterday for 4 devices.

BUT: this is the risk of using the rolling and the price of having the newest features :-)

**Comment by caco3** [comment]
@jomjol Do we understand why they get bricked?Can we solve this before a new release?

@cbho I also love to live on the edge, but please only do it when a rescue action is possible with small effort :)

**Comment by jomjol** [comment]
Well - I always test them on 4 devices. But sometimes I oversee something, and then we are in trouble and only a hard reset with flashing helps. 

If the device is at least booting until server start and uptime is about 2-3 minutes, there would be manual remote options. But even I don't use them. They are rather complicated and I'm not going to document this, because maxim 1 out of 100 users would be able to follow this and for all the other 99 I would be support all day long.

Please keep in mind that this is
1) A very limited device (4 MB RAM, 4 MB ROM) --> no option for a failback system for flashing
2) This is a voluntary shared solution, developed for personal purpouse and not commercial at all.
If you need a stable and absolutly low risk professional solution, this is not the right device.

**Comment by cbho** [comment]
I'm totally aware of the overall conditions for using this - I'm absolutely not trying to argue with that - this is only suggestion for the good of the project...
What I just meant was, that if there is a way to do it, it would be nice to know how - if that could save me (and possibly others from the hassle of the unmounting process etc. - and thereby possible save e.g. @jomjol from being flooded by new issues on that account ;-) ).

As I experienced it, the problem was during the upload of files.
My thinking was:
If you still have access to the file server and can upload the relevant files to the device, then it's a matter of activating the update on the device (which I haven't found a way to do except using the OTA page - but that button couldn't be used, when the uplaod failed).

Anyway, as said: Only a suggestion - sorry if it sounded like a demand or anything like that.

**Comment by caco3** [comment]
@jomjol I don't know how the remote thing would work you mention. As for the REST/HTML part: As long as the REST API responds, we should be able to update, independently if the HTML is broken.

I will create a python script which will communicate directly with the REST API. That's also useful for testing and when you want to update often.

**Comment by jomjol** [comment]
@caco3 basically it is the same idea (REST API). but I don't use it manually. For me it is easier to unmount and flash manually.

**Comment by caco3** [comment]
so remote = REST?

I will create a python tool to do that. we can also build an exe out of it, so its easy to use for novices.

**Comment by jomjol** [comment]
yes!

**Comment by caco3** [comment]
I started to write a python tool, The upload already works, but i cant flash it because of https://github.com/jomjol/AI-on-the-edge-device/issues/973 :(
